name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print build message
      run: echo "build job"

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print deploy message
      run: echo "deploy job"
   
