name: Bots-CI
on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    steps:
    - uses: actions/checkout@v2
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
       files: 'src/Bot/App.config'
      env:
       money_bot_token: ${{ secrets.TELEGRAM_MONEY_BOT_TOKEN }}
       youtube_bot_token: ${{ secrets.TELEGRAM_YOUTUBE_BOT_TOKEN }}
    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
          dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Codecov
      uses: codecov/codecov-action@v1
    - name: Publish
      run: |
        cd src/Bot
        dotnet publish --no-restore -c release -o ./publish
        tar czf publish.gz publish
    - name: Deliver
      uses: appleboy/scp-action@master
      env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      with:
          source: "src/Bot/publish.gz"
          target: "~/"
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          script: |
            cd ~/src/Bot
            tar xf publish.gz
            cd publish
            tmux kill-ses -t Bot 2>/dev/null
            tmux new -d -s 'Bot' './Bot'
