name: Bots-CI
on:
  push:
    branches: [ master ]
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    steps:      
    - uses: actions/checkout@v2
    - name: Setup .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
          dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: |
        cd src/Bot
        dotnet publish --no-restore -c release -o ./publish
        ls -l
        tar cf publish.tar publish
        ls -l
        gzip publish.tar
        ls -l
#   deploy:
#     runs-on: ubuntu-latest
#     needs: [build_and_test]
#     steps:
#     - name: Transfer
#       uses: appleboy/scp-action@master
#       env:
#           HOST: ${{ secrets.SSH_HOST }}
#           USERNAME: ${{ secrets.SSH_USERNAME }}
#           PORT: 22
#           KEY: ${{ secrets.SSH_KEY }}
#       with:
#           source: "*"
#           target: "~/deploy/code"
    
